ADRESSE = $(HOME)/Master_CSM/modèle_cours_latex
ADRESSE_COURS := $(shell ./adresse.sh)

cours.tex: logo.jpg
	cp "$(ADRESSE)/cours.tex" "$(ADRESSE_COURS)/"
	
logo.jpg:
	cp "$(ADRESSE)/logo.jpg" "$(ADRESSE_COURS)/"
	
